import twitterClient from "../twc";

const doRespond = async ({ mediaId, videoId, videoUrl }: any) => {
  try {
    const tweetId = videoId.split("TWITTER-")[1];

    await twitterClient.v1.tweet(
      `Video response generated by Motionbox: DM me if you're a developer looking for a video SDK! Download Video: ${videoUrl}`,
      {
        media_ids: mediaId,
        in_reply_to_status_id: tweetId,
      }
    );
  } catch (e) {
    console.log(
      `Error responding back to the initial Twitter thread ${JSON.stringify(e)}`
    );
  }
};

export default doRespond;
